### ISSUE TITLE
Got "sh: line 5: [: !=: unary operator expected"

### ISSUE THREAD

**Issue by den-vasyliev** [ivanloktionov/pre-commit-gitleaks#1]
`curl https://raw.githubusercontent.com/ivanloktionov/pre-commit-gitleaks/main/pre-commit | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1873  100  1873    0     0  21774      0 --:--:-- --:--:-- --:--:-- 30209
sh: line 5: [: !=: unary operator expected
Gitleaks hooks config is enabled, continue then...
8.16.4
Gitleaks is installed

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:35PM INF 0 commits scanned.
10:35PM INF scan completed in 103ms
10:35PM INF no leaks found`

**Comment by ivanloktionov** [comment]
It appears that the variable $gitleaksEnabled might be empty or not set, causing the error.
Changed to the following condition:

if [ "$gitleaksEnabled" != "enable" ]

Should be fixed
